.gitlab-ci.yml
Change the elixir version to 1.14 in gitlab ci
=> fix: elixir version in gitlab ci

lib/wraft_doc/template_assets.ex, lib/wraft_doc_web/controllers/template_asset_controller.ex, lib/wraft_doc_web/router.ex, lib/wraft_doc_web/views/template_asset_view.ex
- added API to list and download zip template zip from  **wraft.app/t/:file_name**
- update create template_asset to handle the URL of zip from wraft.app domain 
- fixed conflicting name error while importing template from zip file
- solves the conflicting name issues while creating template asset, increment name with number according to existing names
- can import zip file through public URL or as a file
tested with postman for each endpoints
=> feat: template-asset-enhancement

docker-compose.yml
fix document build fails  while up with docker compose
=> add XELATEX_PATH in docker compose file

.github/workflows/lint-pr-title.yml
=> feat(ci): validate pr request title

.github/workflows/lint-pr-title.yml, lib/wraft_doc/kaffy.ex, lib/wraft_doc/template_assets.ex, lib/wraft_doc/template_assets/template_asset.ex, lib/wraft_doc/template_assets/wraft_json.ex, lib/wraft_doc_web/admin/template_asset_admin.ex, lib/wraft_doc_web/controllers/template_asset_controller.ex, lib/wraft_doc_web/router.ex, lib/wraft_doc_web/uploaders/template_asset_thumbnail_uploader.ex, lib/wraft_doc_web/uploaders/template_asset_uploader.ex, lib/wraft_doc_web/views/template_asset_view.ex, priv/repo/migrations/20241120165634_add_file_entires_to_template_asset.exs
added thumbnail for template asset
implemented admin page for public template asset
improved template asset missing items handling and accepts custom items from user
=> feat: add screenshot and admin page for public template in template asset

priv/slugs/pletter/template.tex
Fix inconsistency in alignment of background image for generated document in the case of pletter.
Generate a document with variant layout type pletter and observe if the alignment of the background image is in the center.
=> fix: incorrect aligned for generated document

.env.example, config/config.exs, config/dev.exs, config/prod.exs, lib/wraft_doc/billing/paddle_api.ex
added paddle url to config file
=> chore: add paddle url to config

lib/wraft_doc_web/controllers/organisation_controller.ex, lib/wraft_doc_web/views/organisation_view.ex
Return info on whether the user is already member of organisation on organisation invite verification api.
* Tested through api client to ensure the correct output.
=> fix: add organisation membership status in token verification api

lib/wraft_doc/billing/billing.ex, lib/wraft_doc_web/admin/coupon_admin.ex, lib/wraft_doc_web/admin/enterprise_plan_admin.ex, lib/wraft_doc_web/admin/plan_admin.ex, lib/wraft_doc_web/admin/user_admin.ex, lib/wraft_doc_web/router.ex, priv/repo/migrations/20250212102142_alter_user_references_in_basic_profile.exs
Fix delete user from admin module, user's personal organisation too will be deleted.
Fix organisation delete issues
Fixes #(issue number)
WRA-372
WRA-341
=> chore: fix delete user from admin module

.env.example, config/config.exs, lib/wraft_doc/documents/documents.ex
Add backend url env to handle adding image dynamically.
Enables dynamically adding image url to the generated document.
Tested via UI to ensure that the document is generated with images.
=> fix: add backend url as env variable for image generation

Dockerfile, lib/wraft_doc/documents/documents.ex, priv/pandoc_filters/s3_image.lua
Fixes the image filter path issue and addresses compatibility problems with Docker's Lua configuration.
The changes are required to resolve errors related to image filter paths and to fix the Docker Lua configuration issue that was causing failures.
- The image base path issue was tested by running the application with various image inputs to ensure they are processed correctly based on the proper base path.
- The Docker Lua issue was tested by rebuilding the Docker containers and verifying that Lua scripts run without errors.
=> fix: resolve image filter path issue and docker lua compatibility

lib/wraft_doc/release.ex
=> fix: seed import error in docker

lib/wraft_doc/doc_conversion.ex, lib/wraft_doc/utils/markdown_to_prosemirror.ex
This fix ensures that pandoc_path is properly resolved by checking for its existence in multiple locations, including environment variables, system paths, and default locations. This improves compatibility across different environments, including Docker and local development setups.
=> fix: correctly resolve pandoc_path in docker

lib/wraft_doc/blocks/block.ex, lib/wraft_doc/documents/instance.ex, lib/wraft_doc/forms/form.ex, lib/wraft_doc/pipelines/pipeline.ex, lib/wraft_doc/search/encoder.ex, lib/wraft_doc/search/formatter.ex, lib/wraft_doc/search/presets.ex, lib/wraft_doc/search/typesense.ex, lib/wraft_doc/search/typesense_server.ex, lib/wraft_doc_web/controllers/block_controller.ex, lib/wraft_doc_web/controllers/form_controller.ex, lib/wraft_doc_web/controllers/instance_controller.ex, lib/wraft_doc_web/controllers/pipeline_controller.ex, lib/wraft_doc_web/controllers/search_controller.ex, lib/wraft_doc_web/views/search_view.ex
Added Document , pipeline , block and form search feature
Improve search functionality
terminal and apis
Add any other context about the pull request here.
=> feat: typesense for document, pipline ,forms and block

lib/wraft_doc/search/typesense_server.ex, lib/wraft_doc_web/controllers/search_controller.ex, lib/wraft_doc_web/router.ex
added a feature for superadmin to reindex typesense
gives the ability to reindex typesense search context , helpful for fixing some issues and to restart the server
api calls
=> feat: typesense reindex

lib/wraft_doc/search/encoder.ex
Document not indexing in typesense production
- Document indexing by typesense was not loading in UI, so it was not possible to search for documents.
- Tested via terminal and api calls as well as UI 
- Reproduced the testing scenario by creating a variant and generating a few documents with it and then deleting the created variant there after.
=> fix: documents not indexing

lib/wraft_doc/assets/assets.ex, lib/wraft_doc/frames/frame.ex, lib/wraft_doc/frames/frames.ex, lib/wraft_doc/kaffy.ex, lib/wraft_doc/utils/file_helper.ex, lib/wraft_doc_web/admin/frame_admin.ex, priv/repo/migrations/20250317053316_update_frame_add_file_size.exs
Add frame admin module
testing in kaffy interface and build document with wraft UI
=> feat: frame admin module

lib/wraft_doc/user/account.ex
Hotfix : when user is registered multiple subscriptions are created, cause failure while retrieving
Fixes #(issue number)
=> fix: remove redundant subcription

lib/wraft_doc_web/controllers/approval_system_controller.ex, lib/wraft_doc_web/controllers/billing_controller.ex, lib/wraft_doc_web/controllers/content_type_role_controller.ex, lib/wraft_doc_web/controllers/engine_controller.ex, lib/wraft_doc_web/controllers/membership_controller.ex, lib/wraft_doc_web/controllers/organisation_controller.ex, lib/wraft_doc_web/controllers/payment_controller.ex, lib/wraft_doc_web/controllers/role_group_controller.ex, priv/repo/data/rbac/editor_permissions.csv, priv/repo/data/rbac/permissions.csv
editor permission was updated and some minor fixed
minor bugfix
Via Database and frontend
=> refactor: clean up unused permissions

lib/wraft_doc_web/uploaders/propic_uploader.ex
Fixed the Image Bug after username was updated
the issue where image is not  vivible after the username was updated  in setting
Via UI and Minio
the name of minio storage for profile pic was updated to use user_id instead of user_name
=> fix: profile_pic upload

lib/wraft_doc/utils/prosemirror_to_markdown.ex, priv/slugs/contract/default.typst, priv/slugs/pletter/default.typst
Fixed tables in typst
Fixed converting list into markdown
tested in local.
=> fix: tables in typst slug

lib/wraft_doc/assets/assets.ex, lib/wraft_doc/frames/frames.ex, lib/wraft_doc_web/admin/frame_admin.ex, lib/wraft_doc_web/controllers/frame_controller.ex
Added update frame option in Kaffy admin panel
Through Kaffy admin UI
=> feat: add update frame in frame admin

lib/wraft_doc/utils/prosemirror_to_markdown.ex
Fixed table column width, now user resize it will reflect in output
Fixed bullet listing in table cell
manually tested with wraft UI
=> fix: editor table column width

lib/wraft_doc/documents/documents.ex, lib/wraft_doc/utils/prosemirror_to_markdown.ex, priv/pandoc_filters/pagebreak_typst.lua, priv/pandoc_filters/s3_image_typst.lua, priv/slugs/contract/template.tex, priv/slugs/pletter/template.tex
fix: underline
fix: italic
fix: strike-through in latex
fix: pagebreak in typst
manually tested with UI
=> fix: editor text style formatting

config/runtime.exs
This pull request adds the initial configuration for [Sentry](https://sentry.io/) to enable error tracking and monitoring in the application. This includes necessary settings and environment variables required to integrate Sentry with the existing codebase.
Integrating Sentry helps monitor application errors in real-time and improves debugging efficiency. It is part of our ongoing effort to improve observability and reliability.
- Verified that the application starts successfully with the new Sentry configuration.
- Triggered a sample error to confirm that it is reported to the Sentry dashboard.
- Checked environment variable loading and fallback behavior.
- Ensure SENTRY_DSN is set in environment variables before deploying.
=> chore: add sentry configuration

lib/wraft_doc/documents/documents.ex, lib/wraft_doc_web/controllers/instance_controller.ex, lib/wraft_doc_web/views/instance_view.ex
This pull request improves the handling of Pandoc execution errors by adding better error interpretation and logging. it failed to provide clear or actionable error messages when Pandoc failed. This update ensures that errors are captured, parsed (if possible), and logged meaningfully.
Pandoc errors were unclear, making debugging difficult. This update improves error messages for better visibility and easier troubleshooting.
This change does not modify Pandoc behavior itself but improves how its errors are surfaced and reported to developers.
=> chore: handle pandoc execution errors

lib/wraft_doc/client/minio.ex, lib/wraft_doc/documents/documents.ex, lib/wraft_doc_web/controllers/instance_controller.ex, priv/pandoc_filters/s3_image_typst.lua, priv/slugs/pletter/template.tex
Add error handling for minio file upload
Fixed error in document deletion
Fixed latex pletter header section issues
Tested locally with Wraft UI in dev environment
=> fix: minio file upload 413 error handling

lib/wraft_doc/documents/signatures.ex
Multiple signers can sign on the same document pdf.
Ensures that it is possible to sign on the same document pdf by multiple signers.
Tested locally via UI.
=> fix: multiple signers on the same document

lib/wraft_doc/documents/documents.ex, lib/wraft_doc/logic_pipeline/pipeline_runner.ex
Fixed issue in loading document and details
WRA-409
Tested with Wraft UI
=> fix: loading pdf and document details

lib/wraft_doc/billing/coupon.ex, lib/wraft_doc/organisation/plan.ex, lib/wraft_doc/waiting_lists/waiting_list.ex, lib/wraft_doc/waiting_lists/waiting_lists.ex, lib/wraft_doc_web/admin/coupon_admin.ex, lib/wraft_doc_web/admin/enterprise_plan_admin.ex, lib/wraft_doc_web/admin/plan_admin.ex, lib/wraft_doc_web/admin/template_asset_admin.ex, lib/wraft_doc_web/admin/waiting_list_admin.ex, lib/wraft_doc_web/controllers/health_controller.ex, lib/wraft_doc_web/router.ex, priv/repo/migrations/20250603063710_alter_waiting_list_include_modified_by.exs, priv/repo/migrations/20250603102039_alter_plan_table_add_creator.exs, priv/repo/migrations/20250603114521_alter_coupon_add_creator.exs
- Added support for referencing internal users.
- Introduced a new health check API.
- Enhanced the "waiting list" feature with modified_by tracking.
- Included creator information in Plan and Coupon models.
- Manually tested via the admin panel for all new and modified features.
=> feat: add internal user references for admin resources

lib/wraft_doc/documents/documents.ex, lib/wraft_doc_web/controllers/instance_controller.ex, lib/wraft_doc_web/controllers/search_controller.ex, lib/wraft_doc_web/router.ex, lib/wraft_doc_web/views/instance_view.ex
Added API for contract value chart visualization.
Manually tested using Postman to validate API response, chart data structure, and edge cases.
=> feat: add visualization for contract value data

lib/wraft_doc_web/admin/waiting_list_admin.ex
Fix waiting list admin show entry
Kaffy admin UI
=> fix: waiting list admin show entry

lib/wraft_doc/documents/documents.ex, lib/wraft_doc_web/controllers/instance_controller.ex, lib/wraft_doc_web/views/flow_view.ex, lib/wraft_doc_web/views/instance_view.ex
feat: enhance instance and flow rendering in API responses
=> feat: enhance instance and flow rendering in API responses

lib/wraft_doc/ai_agents/ai_agents.ex, lib/wraft_doc/ai_agents/tools/doc_extraction.ex, lib/wraft_doc/ai_agents/tools/doc_refinement.ex, lib/wraft_doc/ai_agents/tools/doc_suggestion.ex, lib/wraft_doc/ai_agents/tools/tool.ex, lib/wraft_doc_web/controllers/ai_tool_controller.ex
Improved ai agent error handling
Added tool macro template for toold
Tested in local with PostmanAPi
=> refactor: improve ai agent error reponse handling

lib/wraft_doc/comments/comment.ex, lib/wraft_doc/comments/comments.ex, lib/wraft_doc/documents/documents.ex, lib/wraft_doc_web/controllers/comment_controller.ex, lib/wraft_doc_web/router.ex, lib/wraft_doc_web/views/comment_view.ex, priv/repo/migrations/20250701060053_update_comment_table_add_resolver.exs
Add comment resolve api.
Tested with postman API, swagger, wraft UI
=> feat: add comment resolve

lib/wraft_doc/documents/signatures.ex, lib/wraft_doc_web/controllers/signature_controller.ex, priv/slugs/pletter/template.tex
* Enhances error handling on build on signing
* Handles the build for eforms in the case of pletter scenario
Fixes edge cases on build on signing.
Tested locally via  UI.
=> fix: document build on signing improved error handling

config/config.exs, lib/wraft_doc/organisation/organisation.ex, lib/wraft_doc/seed_personal_organisations.ex, lib/wraft_doc/user/user_organisation.ex, lib/wraft_doc/workers/scheduled_worker.ex, lib/wraft_doc_web/admin/organisation_admin.ex, priv/repo/migrations/20250723044103_seed_personal_organisation.exs, priv/repo/migrations/20250723103212_update_organisation_add_modifier.exs
Add modified user to organisation, remove personal organisation from admin panel indexing
Used Kaffy admin panel for testing
=> fix: user personal organisation issue

config/config.exs, config/prod.exs, config/runtime.exs, docker-compose.yml, lib/wraft_doc/documents/signatures.ex, lib/wraft_doc/notifications/delivery.ex, lib/wraft_doc/notifications/notifications.ex, lib/wraft_doc_web/views/user_view.ex
Refactored digital signature configuration from compile-time to runtime for better security and deployment flexibility. Updated environment variables, enhanced error handling, and improved null safety across the application.
Fixes #127
- Digital signature functionality with runtime config
- Docker Compose with updated environment variables
=> fix: compile-time vs runtime config mismatch for doc_signer.p12

config/prod.exs, docker-compose.yml, entrypoint_dev.sh, lib/mix/tasks/wraft.permissions.ex, lib/wraft_doc/blocks/block.ex, lib/wraft_doc/content_types/content_type.ex, lib/wraft_doc/data_templates/data_template.ex, lib/wraft_doc/documents/instance.ex, lib/wraft_doc/forms/form.ex, lib/wraft_doc/layouts/layout.ex, lib/wraft_doc/organisation/flow.ex, lib/wraft_doc/pipelines/pipeline.ex, lib/wraft_doc/search/encoder.ex, lib/wraft_doc/themes/theme.ex, lib/wraft_doc_web/views/user_view.ex
to fix the some errors and warning related with typesense and permission 
While hosting the backend in docker different warnings and errors where being populated m this pull request aims to handle it
- improving the performance and debugging capabilities of wraft by minimising warnings and errors 
- via terminal and docker testing
=> fix: seeding errors and warning in docker

lib/wraft_doc/utils/prosemirror_to_markdown.ex
Handles nested list conversion
Tested in local with wraft UI
=> chore: refactor list node to handle nested lists

lib/wraft_doc/invited_users/invited_user.ex, lib/wraft_doc/invited_users/invited_users.ex, lib/wraft_doc/organisation/enterprise.ex, lib/wraft_doc_web/controllers/organisation_controller.ex, lib/wraft_doc_web/router.ex, lib/wraft_doc_web/views/organisation_view.ex, priv/repo/migrations/20250804192238_create_invite_users_roles_table.exs
Add invite users index, resend invite, revoke invite 
With postman
=> feat: add organisation pending invite list with resend and revoke actions

config/config.exs, config/dev.exs, config/prod.exs, lib/wraft_doc/documents/reminders.ex, lib/wraft_doc/webhooks/event_trigger.ex, lib/wraft_doc/webhooks/webhook.ex, lib/wraft_doc/webhooks/webhook_log.ex, lib/wraft_doc/webhooks/webhooks.ex, lib/wraft_doc/workers/webhook_cleanup_worker.ex, lib/wraft_doc/workers/webhook_worker.ex, lib/wraft_doc_web/controllers/comment_controller.ex, lib/wraft_doc_web/controllers/fallback_controller.ex, lib/wraft_doc_web/controllers/instance_controller.ex, lib/wraft_doc_web/controllers/webhook_controller.ex, lib/wraft_doc_web/router.ex, lib/wraft_doc_web/views/webhook_view.ex, priv/repo/data/rbac/permissions.csv, priv/repo/migrations/20250614120000_create_webhooks.exs, priv/repo/migrations/20250614121000_create_webhook_logs.exs
Implements a comprehensive webhook system for Wraft to enable real-time notifications for document lifecycle events.
Adds webhook functionality to allow organizations to receive notifications when document events occur (creation, completion, signing, etc.).
- **Webhook Management**: CRUD operations for organization webhooks
- **Event Triggering**: Automatic webhook triggers for document state changes
- **Background Processing**: Asynchronous webhook delivery via Oban workers
- **Logging**: Complete webhook execution tracking and cleanup
- **API Endpoints**: RESTful webhook management interface
=> feat: add webhook system with event triggers and background processing

lib/wraft_doc/documents/documents.ex, lib/wraft_doc/utils/prosemirror_to_markdown.ex, lib/wraft_doc_web/views/instance_view.ex
- Fix prosemirror to markdown old list conversion
- Add white space for placeholder 
Wraft UI and local Wraft Server
=> fix: build fail prosemirror list conversion

lib/wraft_doc/assets/assets.ex, lib/wraft_doc_web/uploaders/asset_uploader.ex
Fix pdf upload fail when name have space
Wraft UI and backend
=> fix: format layout pdf file name with special chars
